typeMeta:
  kind: Policy
  version: v1alpha
  package: vmware.tanzu.mc.v1alpha.workspace.policy
fullName:
  name: allow-registry-policy
  workspaceName: acme-fitness-prod
spec:
  policyType: image-policy
  recipeName: allow-registry
  inputValues:
    registry_repos:
      list:
        values:
        - str: harbor.acme-fitness.com
